Fix module.require error throwing on Linux (#1173)
Currently module loading throw error below root when it should not.

$ iotjs ../some.js

uncaughtException: Error: Requested path is below root:

IoT.js-DCO-1.0-Signed-off-by: Sanggyu Lee sg5.lee@samsung.com