tizenrt: Disable debugger code if not enabled
Observed build issue on TizenRT (2.0+):

    iotjs.c:58: undefined reference to `jerryx_debugger_tcp_create'
    iotjs.c:59: undefined reference to `jerryx_debugger_ws_create'
    iotjs.c:58: undefined reference to `jerryx_debugger_after_connect'

The whole part is disabled,
even if only jerry-ext functions are not linked.

This should not cause any issue on earlier versions of TizenRT

Change-Id: Id88c745c9712f6f620bbd200f493397572174ce6
Forwarded: https://github.com/Samsung/iotjs/pull/1795
Origin: https://github.com/Samsung/iotjs/pull/1749
IoT.js-DCO-1.0-Signed-off-by: Philippe Coval p.coval@samsung.com