Disable jerryscript debugger code if not enabled
Observed build issue on TizenRT (master branch):

    iotjs.c:58: undefined reference to `jerryx_debugger_tcp_create'
    iotjs.c:59: undefined reference to `jerryx_debugger_ws_create'
    iotjs.c:58: undefined reference to `jerryx_debugger_after_connect'

To avoid unused variable port is logged on error

Bug: https://github.com/Samsung/iotjs/pull/1749
IoT.js-DCO-1.0-Signed-off-by: Philippe Coval philippe.coval@osg.samsung.com