Fixed the close function in gpio
When the close function is called, that returned an error :
uncaughtException: ReferenceError: value is not defined

The value parameter does not exist in the close function and the close callback is called with only one parameter.

IoT.js-DCO-1.0-Signed-off-by: cedricDum duminy.cedric@gmail.com