Fix the close function in gpio, adc and uart
When the close function is called, that returned an error :
uncaughtException: ReferenceError: value is not defined

The value parameter does not exist in the close functions.

IoT.js-DCO-1.0-Signed-off-by: cedricDum duminy.cedric@gmail.com