build: Update TizenRT to 2.0_Public_M2
Because current version of TizenRT in IoT.js docker image is oudated,
let's fetch tag from upstream at build time,
to speed up build time, this part can be eventually removed
if image is updated with latest TizenRT's sources.

Use iotjs's defconfig as default config instead of file:
"tizenrt_release_config"
from container:
https://hub.docker.com/r/iotjs/ubuntu/

Is this file tracked anywhere?

Later debug, release configs can tracked in IoT.js's source tree,
and used as desired, for performance benchmarking.

jerryx extra lib has been dropped for now,
this should be reintroduced later (once TizenRT upgrade IoT.js ?)

Bug: https://github.com/Samsung/iotjs/issues/1777
IoT.js-DCO-1.0-Signed-off-by: Philippe Coval p.coval@samsung.com

Disable debuger code if not enabled

Observed build issue on TizenRT (master):

    iotjs.c:58: undefined reference to `jerryx_debugger_tcp_create'
    iotjs.c:59: undefined reference to `jerryx_debugger_ws_create'
    iotjs.c:58: undefined reference to `jerryx_debugger_after_connect'

The whole part is disabled,
even if only jerry-ext functions are not linked (on Tizen:RT master).

Change-Id: Id88c745c9712f6f620bbd200f493397572174ce6
Forwarded: https://github.com/Samsung/iotjs/pull/1749
Origin: https://github.com/TizenTeam/iotjs/
IoT.js-DCO-1.0-Signed-off-by: Philippe Coval philippe.coval@osg.samsung.com

tizenrt: Update defconfig from TizenRT 2.0

Align to TizenRT default config, but disable SSS for ARTIK053

Bug: https://github.com/Samsung/iotjs/issues/1777
IoT.js-DCO-1.0-Signed-off-by: Philippe Coval p.coval@samsung.com

tizenrt: Relocate downstream Makefile to config dir (along Kconfig)

[Philippe Coval]

After some (recent) refactoring in build script,
This file was over imported iotjs module in TizenRT.

Like done previously with Kconfig file,
it will be better to minimize downstream patches.

One benefit to have those build related files,
is that then IoT.js can be upgraded into TizenRT
by just cloning iotjs's again into subdir:
TizenRT/external/iotjs

Note: Extra minor changes has been done over TizenRT's patch
to make some options overridable from env var (profile file...)

[Sunghan Chang]

Makefile: move IoT.js-specific build step to IoT.js folder

Because Makefile.unix has TizenRT-common build step,
it is not good including IoT.js-specific step.
Let's add Makefile in IoT.js and execute all of step in it.

Thanks-to: sunghan-chang <sh924.chang@samsung.com>
Change-Id: Iddeb272dc6ad6c283ccad9f92bf02754f9ba3240
Bug-TizenRT: https://github.com/Samsung/TizenRT/pull/2111
Origin: https://github.com/Samsung/TizenRT/commit/bbd3cdbd498ff11eeca3f021496423cc0222497e
Relate-to: https://github.com/Samsung/iotjs/issues/1726
Forwarded: https://github.com/Samsung/iotjs/pull/1732
IoT.js-DCO-1.0-Signed-off-by: Philippe Coval p.coval@samsung.com