tizenrt: Disable debugger code if not enabled (#1798)
Observed build issue on TizenRT (2.0+):

    iotjs.c:58: undefined reference to `jerryx_debugger_tcp_create'
    iotjs.c:59: undefined reference to `jerryx_debugger_ws_create'
    iotjs.c:58: undefined reference to `jerryx_debugger_after_connect'

The whole part is disabled,
even if only jerry-ext functions are not linked.

This should not cause any issue on earlier versions of TizenRT

debugger: Disable code if not desired

This part is not as critical for TizenRT,
but will help to make iotjs smaller.

Thanks-to: Daeyeon Jeong daeyeon.jeong@samsung.com
Relate-to: https://github.com/Samsung/iotjs/pull/1795
Forwarded: https://github.com/Samsung/iotjs/pull/1798
IoT.js-DCO-1.0-Signed-off-by: Philippe Coval p.coval@samsung.com